name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: List Folder
      run: ls -lah
    - name: enter target
      run: cd target
    - name: results
      run: ls -lah

    - name: Get Version from pom.xml
      run: |
        version=$(grep -oP '<version>\K[^<]+' pom.xml)
        echo "Version: $version" >> $GITHUB_ENV
      shell: bash

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ env.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/translator-${{ env.version }}-jar-with-dependencies.jar
        asset_name: translator-${{ env.version }}.jar
        asset_content_type: application/java-archive
